# Generated by Django 4.1 on 2025-08-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'affects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AppliesTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'applies_to',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dietplan',
            fields=[
                ('diet_plan_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal', models.CharField(max_length=10)),
                ('total_calories', models.FloatField()),
            ],
            options={
                'db_table': 'dietplan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('calories_burned_per_hour', models.FloatField()),
                ('benefits', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'exercise',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseRestriction',
            fields=[
                ('exercise_restriction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('e_reason', models.CharField(max_length=100)),
                ('e_severity', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'exercise_restriction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodNutrition',
            fields=[
                ('food_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=100)),
                ('calories_100g', models.FloatField()),
                ('protein_100g', models.FloatField()),
                ('fat_100g', models.FloatField()),
                ('carbs_100g', models.FloatField()),
                ('health_benefits', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'food_nutrition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FoodRestriction',
            fields=[
                ('food_restriction_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('f_reason', models.CharField(max_length=100)),
                ('f_severity', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'food_restriction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HealthProblem',
            fields=[
                ('health_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'health_problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Includes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'includes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuffersFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'suffers_from',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('height', models.DecimalField(decimal_places=3, max_digits=4)),
                ('weight', models.DecimalField(decimal_places=3, max_digits=6)),
                ('activity_level', models.IntegerField()),
                ('activity_multiplier', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
