# Generated by Django 4.1 on 2025-09-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0002_customprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomProfile',
        ),
    ]
