# Generated by Django 4.1 on 2025-09-04 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0003_delete_customprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(default=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifestyle.foodnutrition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifestyle.user')),
            ],
            options={
                'db_table': 'food_preference',
            },
        ),
        migrations.CreateModel(
            name='ExercisePreference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allowed', models.BooleanField(default=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifestyle.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifestyle.user')),
            ],
            options={
                'db_table': 'exercise_preference',
            },
        ),
    ]
