# Generated by Django 4.1 on 2025-09-04 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0004_foodpreference_exercisepreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suffersfrom',
            options={'managed': True},
        ),
    ]
