# Generated by Django 4.1 on 2025-09-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lifestyle', '0005_alter_suffersfrom_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suffersfrom',
            options={'managed': False},
        ),
    ]
